/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DirectorRouteImport } from './routes/director'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LoginEmployeeRouteImport } from './routes/login.employee'
import { Route as LoginDirectorRouteImport } from './routes/login.director'

const DirectorRoute = DirectorRouteImport.update({
  id: '/director',
  path: '/director',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginEmployeeRoute = LoginEmployeeRouteImport.update({
  id: '/login/employee',
  path: '/login/employee',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginDirectorRoute = LoginDirectorRouteImport.update({
  id: '/login/director',
  path: '/login/director',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/director': typeof DirectorRoute
  '/login/director': typeof LoginDirectorRoute
  '/login/employee': typeof LoginEmployeeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/director': typeof DirectorRoute
  '/login/director': typeof LoginDirectorRoute
  '/login/employee': typeof LoginEmployeeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/director': typeof DirectorRoute
  '/login/director': typeof LoginDirectorRoute
  '/login/employee': typeof LoginEmployeeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/director' | '/login/director' | '/login/employee'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/director' | '/login/director' | '/login/employee'
  id: '__root__' | '/' | '/director' | '/login/director' | '/login/employee'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DirectorRoute: typeof DirectorRoute
  LoginDirectorRoute: typeof LoginDirectorRoute
  LoginEmployeeRoute: typeof LoginEmployeeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/director': {
      id: '/director'
      path: '/director'
      fullPath: '/director'
      preLoaderRoute: typeof DirectorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/employee': {
      id: '/login/employee'
      path: '/login/employee'
      fullPath: '/login/employee'
      preLoaderRoute: typeof LoginEmployeeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/director': {
      id: '/login/director'
      path: '/login/director'
      fullPath: '/login/director'
      preLoaderRoute: typeof LoginDirectorRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DirectorRoute: DirectorRoute,
  LoginDirectorRoute: LoginDirectorRoute,
  LoginEmployeeRoute: LoginEmployeeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
